### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fyoncle** [InZan17/Unloaded-Activity#29]
Can i know more about your future plans and things you're planning to do for this mod since i am interested in the idea.

It seems very nice and since you mentioned that you would like to fix some stuff before adding compats and stuff i wanted to know how development is going.

**Comment by InZan17** [comment]
Currently I don't have much motivation to work on this project, besides updating it to the latest Minecraft version when I can. I'm also a bit busy with some other stuff.

I still wanna add compats in the future. But I would like to fix an issue first, that no one else but me probably cares about. The issue is the accuracy of copper ageing and water freezing. Which is a bit of a challenge since the odds of copper ageing or water freezing depends on the blocks surrounding them, and those blocks' odds are also affected by the blocks surrounding them, so I have to somehow update them all together, which I am not sure how to implement.

But I'll try to fix it and add compats, but it probably won't happen anytime soon.

**Comment by Fyoncle** [comment]
> Currently I don't have much motivation to work on this project, besides updating it to the latest Minecraft version when I can. I'm also a bit busy with some other stuff.
> 
> I still wanna add compats in the future. But I would like to fix an issue first, that no one else but me probably cares about. The issue is the accuracy of copper ageing and water freezing. Which is a bit of a challenge since the odds of copper ageing or water freezing depends on the blocks surrounding them, and those blocks' odds are also affected by the blocks surrounding them, so I have to somehow update them all together, which I am not sure how to implement.
> 
> But I'll try to fix it and add compats, but it probably won't happen anytime soon.

Got it! Thanks for answering my question :)

Hope you will eventually gain back your motivation :D ❤️
