### ISSUE TITLE
Cause Server LAG

### ISSUE THREAD

**Issue by FelixAgairu** [InZan17/Unloaded-Activity#30]
The UA cause the MTPS from 20 to 50+
[Spark Profile](https://spark.lucko.me/bX3nyybtgA)
[Server Log](https://gist.github.com/FelixAgairu/9788f9ed0eea0f8fca6e4a00424cdad6)

**Comment by InZan17** [comment]
Does the lag happen when you are loading in chunks? If it is, that might be because it has to loop through every block in the chunk to find which ones to simulate, but then it saves the positions and it should be pretty fast the next time it gets loaded. 

You can reduce how many chunks it can loop through per tick by changing `maxChunkUpdates` in the config file or by running `/unloadedactivity config maxChunkUpdates (new value)`. You can also change `maxKnownChunkUpdates` if it's still lagging, but this is for chunks which already have the positions saved.

If it's lagging when you are just standing still, then could you please make sure it's my mod causing the lag and not another one? My mod shouldn't do much if no chunks are being loaded.

**Comment by FelixAgairu** [comment]
Then might not your mod.
Now, the mtps upto 80+ while loading chunks, and stable near 50 standing still.

But first time remove this mod make mtps down to near 20, Dont know why.

**Comment by VaporeonScripts** [comment]
could be cross incompatibility with UA and some other mod

**Comment by FelixAgairu** [comment]
Its drop items, cause heavy server load, 2 player, 50+ drop items.
